-- MySQL Script generated by MySQL Workbench
-- Wed Nov 14 08:40:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TQMagico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TQMagico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TQMagico` DEFAULT CHARACTER SET utf8 ;
USE `TQMagico` ;

-- -----------------------------------------------------
-- Table `TQMagico`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `saldo` DOUBLE NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `logradouro` VARCHAR(150) NOT NULL,
  `anamnese` MEDIUMTEXT NULL,
  `observacao` VARCHAR(300) NULL,
  `data_cadastro` DATE NOT NULL,
  `saldo` DOUBLE NOT NULL,
  `id_usuario_cliente` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `id_usuario_idx` (`id_usuario_cliente` ASC),
  CONSTRAINT `id_usuario_cl`
    FOREIGN KEY (`id_usuario_cliente`)
    REFERENCES `TQMagico`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`telefone` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `id_cliente_telefone` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  PRIMARY KEY (`id_telefone`),
  INDEX `id_cliente_idx` (`id_cliente_telefone` ASC),
  CONSTRAINT `id_cliente_te`
    FOREIGN KEY (`id_cliente_telefone`)
    REFERENCES `TQMagico`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`agenda` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `data_hora` TIMESTAMP NOT NULL,
  `valor_combinado` DOUBLE NULL,
  `id_cliente_agenda` INT NOT NULL,
  `id_usuario_agenda` INT NOT NULL,
  `realizado` TINYINT NOT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `id_cliente_idx` (`id_cliente_agenda` ASC),
  INDEX `id_usuario_idx` (`id_usuario_agenda` ASC),
  CONSTRAINT `id_cliente_ag`
    FOREIGN KEY (`id_cliente_agenda`)
    REFERENCES `TQMagico`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario_ag`
    FOREIGN KEY (`id_usuario_agenda`)
    REFERENCES `TQMagico`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`fornecedor` (
  `id_fornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `contato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_fornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`contas` (
  `id_conta` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(300) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `status` TINYINT NOT NULL,
  `id_usuario_contas` INT NOT NULL,
  `id_fornecedor` INT NOT NULL,
  PRIMARY KEY (`id_conta`),
  INDEX `id_usuario_idx` (`id_usuario_contas` ASC),
  INDEX `id_fornecedor_idx` (`id_fornecedor` ASC),
  CONSTRAINT `id_usuario_co`
    FOREIGN KEY (`id_usuario_contas`)
    REFERENCES `TQMagico`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_fornecedor_co`
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `TQMagico`.`fornecedor` (`id_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`caixa` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `valor` DOUBLE NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `data_registro` VARCHAR(100) NOT NULL,
  `id_usuario_caixa` INT NOT NULL,
  `id_cliente_caixa` INT NULL,
  PRIMARY KEY (`id_registro`),
  INDEX `id_usuario_idx` (`id_usuario_caixa` ASC),
  INDEX `id_cliente_idx` (`id_cliente_caixa` ASC),
  CONSTRAINT `id_usuario_ca`
    FOREIGN KEY (`id_usuario_caixa`)
    REFERENCES `TQMagico`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente_ca`
    FOREIGN KEY (`id_cliente_caixa`)
    REFERENCES `TQMagico`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `preco` DOUBLE NOT NULL,
  `estoque` INT NOT NULL,
  `id_usuario_produtos` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `id_usuario_idx` (`id_usuario_produtos` ASC),
  CONSTRAINT `id_usuario_pr`
    FOREIGN KEY (`id_usuario_produtos`)
    REFERENCES `TQMagico`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`produtos_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`produtos_caixa` (
  `id_pro_cai` INT NOT NULL AUTO_INCREMENT,
  `id_produto_pc` INT NOT NULL,
  `id_registro_pc` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id_pro_cai`),
  INDEX `id_caixa_idx` (`id_registro_pc` ASC),
  INDEX `id_produto_idx` (`id_produto_pc` ASC),
  CONSTRAINT `id_caixa`
    FOREIGN KEY (`id_registro_pc`)
    REFERENCES `TQMagico`.`caixa` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_produto`
    FOREIGN KEY (`id_produto_pc`)
    REFERENCES `TQMagico`.`produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`servicos` (
  `id_servico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `descricao` VARCHAR(200) NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id_servico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`agenda_servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`agenda_servicos` (
  `id_age_serv` INT NOT NULL AUTO_INCREMENT,
  `id_evento_as` INT NOT NULL,
  `id_servico_as` INT NOT NULL,
  PRIMARY KEY (`id_age_serv`),
  INDEX `id_evento_idx` (`id_evento_as` ASC),
  INDEX `id_servico_idx` (`id_servico_as` ASC),
  CONSTRAINT `id_evento`
    FOREIGN KEY (`id_evento_as`)
    REFERENCES `TQMagico`.`agenda` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_servico`
    FOREIGN KEY (`id_servico_as`)
    REFERENCES `TQMagico`.`servicos` (`id_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TQMagico`.`agenda_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TQMagico`.`agenda_caixa` (
  `id_age_cai` INT NOT NULL AUTO_INCREMENT,
  `id_evento_ac` INT NOT NULL,
  `id_registro_ac` INT NOT NULL,
  `preco_cobrado` DOUBLE NULL,
  PRIMARY KEY (`id_age_cai`),
  INDEX `id_evento_idx` (`id_evento_ac` ASC),
  INDEX `id_registro_idx` (`id_registro_ac` ASC),
  CONSTRAINT `id_evento_a_c`
    FOREIGN KEY (`id_evento_ac`)
    REFERENCES `TQMagico`.`agenda` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_registro_a_c`
    FOREIGN KEY (`id_registro_ac`)
    REFERENCES `TQMagico`.`caixa` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*Alterações*/
INSERT INTO usuario VALUES (NULL, 'admin', 'admin', 500);
ALTER TABLE caixa ADD COLUMN (hora TIME NOT NULL);
ALTER TABLE telefone MODIFY numero VARCHAR(17) UNIQUE KEY;
ALTER TABLE agenda DROP COLUMN data_hora;
ALTER TABLE agenda ADD COLUMN(data DATE NOT NULL, hora VARCHAR(15) NOT NULL);
/*Necessidade de inserir o primeiro cliente por erro no retornaProximoCodigoCliente do programa*/
INSERT INTO cliente VALUES (NULL, 'Cliente Um', '0', '2018-01-01', '0', '0', '0', '2018-11-28', '0', '1');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;